modLoader="javafml"
loaderVersion="[42,)"
issueTrackerURL="https://github.com/Lykrast/MeetYourFight/issues"
license="MIT License https://github.com/Lykrast/MeetYourFight/blob/master/LICENSE"

[[mods]]
modId="meetyourfight"
version="${file.jarVersion}"
displayName="Meet Your Fight"
displayURL="https://modrinth.com/mod/meet-your-fight"
credits="JTK22 for the Haunted Bell texture, Monkey Warhol, Guifrog, Kain Vinosec, PinpinNeon for their respective songs (resp. CC BY, CC BY, used under licence, commissionned for this mod)"
authors="Lykrast"
description='''
Adds several bosses to fight, each giving you access to unique goodies, such as weapons, armors or curios. Theses bosses won't come to you on their own though, to call them you need to craft the appropriate summoning item.
'''

[[dependencies.meetyourfight]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.meetyourfight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.meetyourfight]]
    modId="curios"
    mandatory=true
    versionRange="[1.19-5.1.0.1,)"
    ordering="NONE"
    side="BOTH"